apiVersion: v1
kind: Pod
metadata:
  name: redis-test
spec:
  affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - minikube
  containers:
    - name: redis-test
      image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/redis:alpine
      command:
        - "sleep"
        - "3600"
