# This rule is not used by the project kflow itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to kflow.io.kflow resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kflow
    app.kubernetes.io/managed-by: kustomize
  name: kflow-viewer-role
rules:
- apiGroups:
  - kflow.io.kflow
  resources:
  - kflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kflow.io.kflow
  resources:
  - kflows/status
  verbs:
  - get
